---
- name: install android sdk dependencies
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - lib32z1
    - libc6-dev-i386
    - openjdk-8-jdk

- name: create android sdk directory in {{ android_home }}
  file:
    path: "{{ android_home }}"
    state: directory

- name: create directory {{ dot_android_folder }}
  file:
      path: "{{ dot_android_folder }}"
      state: directory

- name: create {{ dot_android_folder }}/repositories.cfg"
  file:
      state: touch
      path: "{{ dot_android_folder }}/repositories.cfg"

- name: check {{ android_home }} contents
  command: ls {{ android_home }}
  register: contents

- name: download android sdk and extract to {{ android_home }}
  unarchive:
      src: https://dl.google.com/android/repository/tools_r25.2.4-linux.zip
      dest: "{{ android_home }}/"
      remote_src: true
  when: contents.stdout == ""

- name: append android sdk configuration to user's .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} - ANDROID SDK - ANSIBLE MANAGED BLOCK"
    block: |
        # Android configuration
        export ANDROID_HOME={{ android_home }}
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
        export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1

- name: Install Android SDK tools
  # Using "command" instead of "shell" will crash
  shell: "yes | {{ android_home }}/tools/bin/sdkmanager \"{{ android_sdk_packages|join('\" \"') }}\""
