---
- name: "Install Android SDK dependencies"
  package:
      name: "{{ item }}"
      state: present
  with_list: "{{ android_sdk_dependencies_packages }}"
  become: true

- name: "Create Android SDK directory in {{ android_home }}"
  file:
    path: "{{ android_home }}"
    state: directory

- name: "Create directory {{ dot_android_folder }}"
  file:
      path: "{{ dot_android_folder }}"
      state: directory

- name: "Create {{ dot_android_folder }}/repositories.cfg"
  copy:
      content: ""
      dest: "{{ dot_android_folder }}/repositories.cfg"
      force: no

- name: "Check {{ android_home }} contents"
  command: "ls {{ android_home }}"
  register: contents

- name: "Download Android SDK and extract to {{ android_home }}"
  unarchive:
      src: "https://dl.google.com/android/repository/tools_r25.2.4-linux.zip"
      dest: "{{ android_home }}/"
      remote_src: true
  when: contents.stdout == ""

- name: Append Android configuration to user's .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} - ANDROID SDK - ANSIBLE MANAGED BLOCK"
    block: |
        # Android configuration
        export ANDROID_HOME={{ android_home }}
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
        export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1

- name: Install Android SDK tools
  # Using "command" instead of "shell" will crash
  shell: "yes | {{ android_home }}/tools/bin/sdkmanager \"{{ android_sdk_packages|join('\" \"') }}\""
