---
- name: install gstreamer plugins
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav

- name: install vlc
  package:
    name: vlc
    state: latest
  become: true

- name: install quod libet
  package:
    name: quodlibet
    state: latest
  become: true

- name: install easytag
  package:
    name: easytag
    state: latest
  become: true

- name: uninstall rhythmbox
  package:
    name: rhythmbox
    state: absent
  become: true

- name: install handbrake
  package:
    name: handbrake
    state: latest
  become: true

- name: install simplescreenrecorder
  package:
    name: simplescreenrecorder
    state: latest
  become: true

- name: install kdenlive
  package:
    name: kdenlive
    state: latest
  become: true
