---
- name: Provision Debian
  hosts: all
  roles:
    - apt
    - kernel
    - firewall
    - x260
    - desktop
    - multimedia
    - firefox
    - development
    - virtualization
    - docker
    - python
    - vim
    - node
    - sudo
    - bash
    - git
    - android_sdk
    - google_cloud_sdk
    - heroku
    - aws
