---
- name: install firmware-iwlwifi
  package:
    name: firmware-iwlwifi
    state: latest
    default_release: stretch-backports
  become: true

- name: install firmware-linux
  package:
    name: firmware-linux
    state: latest
    default_release: stretch-backports
  become: true

- name: configure iwlwifi
  copy:
    content: options iwlwifi bt_coex_active=0
    dest: /etc/modprobe.d/iwlwifi.conf
  become: true
