---
- name: install linux-headers-amd64
  package:
    name: linux-headers-amd64
    state: latest
  become: true

- name: install build-essential
  package:
    name: build-essential
    state: latest
  become: true

- name: install virtualbox
  package:
    name: virtualbox
    state: latest
  become: true

- name: install vagrant
  package:
    name: vagrant
    state: latest
  become: true

- name: add user to vboxusers group
  user:
    name: "{{ ansible_env.USER }}"
    append: true
    groups: vboxusers
  become: true

# Vagrant changed the URL the boxes are at and Debian still has an old version
# of Vagrant without updated URL, therefore need to set it manually.
- name: delete old setting of default vagrant server
  blockinfile:
    # It's been fixed on Debian repos, therefore set to "absent".
    state: absent
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# {mark} - VAGRANT - ANSIBLE MANAGED BLOCK"
    block: |
      export VAGRANT_SERVER_URL=https://vagrantcloud.com
